#ifndef mpu_h
#define mpu_h

#include <stdio.h>
#include <stdlib.h>
#include <wiringPi.h>
#include <wiringPiI2C.h>

// Allows the user to configure the power mode and clock source. It also provides a bit for resetting the entire device
// and a bit for disabling the temperature sensor
#define PWR_MGMT_1   0x6B

// This register specifies the divider from the gyro output rate used to generate the sample rate
// rate generated by dividing the gyroscope output rate by SMPLRT_DIV
// Sample rate = Gyroscope output rate / (1 + SMPLRT_DIV)
// By this equation we can see that the bigger the SMPLRT_DIV is then the smallert the resultant Sample rate
#define SMPLRT_DIV   0x19

// This register configures the external Frame Synchronization (FSYNC) pin sampling and the
// Digital Low Pass Filter (DLPF) setting for both the gyroscopes and accelerometers.
#define CONFIG       0x1A

// This register is used to trigger gyroscope self-test and configure the gyroscopes’ full scale range.
#define GYRO_CONFIG  0x1B

// This register enables interrupt generation by interrupt sources.
#define INT_ENABLE   0x38

// Accelerometers Measuraments. Stores the most recent measuraments
// outputed at the Sample rate as defined in register 25
#define ACCEL_XOUT_H 0x3B
#define ACCEL_YOUT_H 0x3D
#define ACCEL_ZOUT_H 0x3F

// Gyroscope Measuraments. Stores the most rcent measuraments
// outputed at the Sample rate as defined in register 25
#define GYRO_XOUT_H  0x43
#define GYRO_YOUT_H  0x45
#define GYRO_ZOUT_H  0x47

typedef struct {
    float x;
    float y;
    float z;
} coordinate;

typedef struct {

    //File descriptor, usefull for error handling stderr, stdin, stdout
    int fd;

    //Properties with the current coordinates of gyroscope and accelerometer
    coordinate gyro;
    coordinate accl;
} mpu;

void mpu_init(mpu *m, int address);

void listen_gyro_coordinate(mpu *m);  // unit: degrees / second
void listen_accl_coordinate(mpu *m);  // unit: g

void mpu_set_sample_rate(mpu *m, int value); //set the sample rate of the clock

#endif